### ISSUE TITLE
DRPAI rate appears to not be corresponding to the "real" rate

### ISSUE THREAD

**Issue by mistyron** [MistySOM/gstreamer1.0-drpai#20]
In the top left, the DRPAI Rate: often times shows 0fps. siometimes it does show 1 fps but it won't ever show a higher rate. I got a couple of screenshots below when the inference (DRPAI) obviously is working: 
![image](https://github.com/MistySOM/gstreamer1.0-drpai/assets/94636867/7abc880c-2484-41ab-adfd-c038b59f114b)
![image](https://github.com/MistySOM/gstreamer1.0-drpai/assets/94636867/1e3996c2-8e88-413a-9612-5e3bb6be13d7)

**Comment by matinlotfali** [comment]
> the inference (DRPAI) obviously is working

Zero means it is working. N/A means it is not working at all.

To be more clear, zero means that each AI is taking more than a second. So like once every 3 seconds which calculates to 0.33 fps and rounds to zero.

### Hint:

Looking at the video rate which is supposed to be 30 fps, it is 9 fps. So I believe there is probably another process that is taking a lot of resources and is reducing the performance of DRP-AI.

**Comment by mistyron** [comment]
> > the inference (DRPAI) obviously is working
> 
> Zero means it is working. N/A means it is not working at all.
> 
> To be more clear, zero means that each AI is taking more than a second. So like once every 3 seconds which calculates to 0.33 fps and rounds to zero.

Ok
> 
> ### Hint:
> Looking at the video rate which is supposed to be 30 fps, it is 9 fps. So I believe there is probably another process that is taking a lot of resources and is reducing the performance of DRP-AI.

Oh okay, interesting! :thinking: I'm suspicious now, that two gstreamer-drpai instances were potentially running in parallel, then. This might be nothing the, let's close this and see if it appears again.
