### ISSUE TITLE
When objects are small, their name label covers the whole box and you can't see them

### ISSUE THREAD

**Issue by matinlotfali** [MistySOM/gstreamer1.0-drpai#28]
See the screenshot below. Should I move the label above the box instead? @mistyron 

![image](https://github.com/MistySOM/gstreamer1.0-drpai/assets/7337168/c8da6f31-1763-48b2-97d8-e92200df77b5)

**Comment by mistyron** [comment]
> See the screenshot below. Should I move the label above the box instead? @mistyron

Yes, I think moving the label above the box would be better

**Comment by mistyron** [comment]
> > See the screenshot below. Should I move the label above the box instead? @mistyron
> 
> Yes, I think moving the label above the box would be better
Also showing the ID will help for development and debugging but should be removed eventually, just display the class name & the accuracy number.
