### ISSUE TITLE
The plugin crashes with SIGSEGV (segmentation violation) when tracking

### ISSUE THREAD

**Issue by matinlotfali** [MistySOM/gstreamer1.0-drpai#29]
With the new tracking algorithm, the plugin crashes at a random time probably because of a threading issue.

**Comment by mistyron** [comment]
> With the new tracking algorithm, the plugin crashes at a random time probably because of a threading issue.

Can you hook up GDB and see where it seg faults in better detail?

**Comment by matinlotfali** [comment]
Resolved in #31
