### ISSUE TITLE
recursive call can result in endless loop

### ISSUE THREAD

**Issue by mistyron** [MistySOM/gstreamer1.0-drpai#46]
Hi Matin,
I spotted something here:
https://github.com/MistySOM/gstreamer1.0-drpai/blob/3ad586988cf5f0eef627d886817ba2320bceb122/gst-plugin/src/drpai_controller.cpp#L245
looks like the default case may call itself recursively with the same argument which will not have a happy ending if it ever happens, will it? 
Also, it's propably worthwhile to include a check that data is set before going  into the switch like:
since catching an error like this is generally - the earlier the better - I'm open to hearing your point though!
``` 
if (!data)
   return; 
```
since you're returning `void`.
Your toughts?

**Comment by matinlotfali** [comment]
# 
> looks like the default case may call itself recursively with the same argument

No that is not a recursive call, but a routing to model-specific handeling.

Note that the class `DRPAI_Controller` is just a controller for the `drpai` model. It makes sure the correct model is loaded and is properly set. Each model is different and has its class derived from `DRPAI_Base` such as `DRPAI_Yolo`, `DRPAI_Deeppose` (not yet merged), and `DRPAI_FOMO` (not yet implemented). 

So it can be seen here that the model library is being loaded dynamically after it is clear which model is chosen:

https://github.com/MistySOM/gstreamer1.0-drpai/blob/3ad586988cf5f0eef627d886817ba2320bceb122/gst-plugin/src/drpai_controller.cpp#L215


# 
> Also, it's propably worthwhile to include a check that data is set before going into the switch

If the value is not set, the gstreamer will throw an error earlier and it won't reach this line.

# 
> Your thoughts?

It obviously needs a lot better code commenting and documentation

**Comment by mistyron** [comment]
Thanks, for addressingthe concerns! As for commenting, yes, I sugest you add comments as you write the code so that you don't have to go back and fill-in comments later on (which rarely happens).
